version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belajar_golang
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_DSN: root:root@tcp(mysql:3306)/belajar_golang

volumes:
  db-data:
